services:
  llm-env:
    build: .
    container_name: llm_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    stdin_open: true   
    tty: true 
